### ISSUE TITLE
Should the golang implementation implement the SQL Valuer interface?

### ISSUE THREAD

**Issue by loreto** [jetpack-io/typeid-go#6]
See: https://pkg.go.dev/database/sql/driver#Valuer

If yes, what should the encoding default to?

Suggested in: https://github.com/jetpack-io/typeid-go/issues/4

**Comment by loreto** [comment]
Note that Scanner is another relevant interface for SQL integration.

**Comment by stevelizcano** [comment]
I recommend that this be done, because it makes typeIDs more difficult to wrangle if you are using a library like SQLC.

The issue is that if you do something like `select * from my_table where id = 'some_id';` , you will get the typeID back. If you specify the sqlc type id like, for example:

```yaml
      - db_type: "doc_id"
        go_type: "go.jetpack.io/typeid.TypeID"
```

It will try and coalesce the return string tuple into the TypeID. It fails, and panics.

Adding this ability—which I think is the `Scan` feature—would be very helpful.

**Comment by loreto** [comment]
Recently committed a PR that adds this. Next release will have this built in.

**Comment by wilsonehusin** [comment]
@stevelizcano 👋🏻 hiya curious how are you integrating TypeID with sqlc? I've been trying with not much success, so I resorted to writing a hacky generator: [typeid-sqlc-shim](https://github.com/wilsonehusin/typeid-sqlc-shim). Ideally I would like to have direct integration from either (or both) sides, without having to maintain this tool 😄

**Comment by loreto** [comment]
> @stevelizcano 👋🏻 hiya curious how are you integrating TypeID with sqlc? I've been trying with not much success, so I resorted to writing a hacky generator: [typeid-sqlc-shim](https://github.com/wilsonehusin/typeid-sqlc-shim). Ideally I would like to have direct integration from either (or both) sides, without having to maintain this tool 😄

@wilsonehusin We implemented `sql.Scanner` and `sql.Valuer` into the main library. See: https://github.com/jetify-com/typeid-go/blob/main/sql.go

Does that not let you do the sqlc integration without a shim?

**Comment by wilsonehusin** [comment]
> > @stevelizcano 👋🏻 hiya curious how are you integrating TypeID with sqlc? I've been trying with not much success, so I resorted to writing a hacky generator: [typeid-sqlc-shim](https://github.com/wilsonehusin/typeid-sqlc-shim). Ideally I would like to have direct integration from either (or both) sides, without having to maintain this tool 😄
> 
> @wilsonehusin We implemented `sql.Scanner` and `sql.Valuer` into the main library. See: https://github.com/jetify-com/typeid-go/blob/main/sql.go
> 
> Does that not let you do the sqlc integration without a shim?

It does, but I would need to use `AnyPrefix`. I was wondering if there is a reasonable setup to make model-specific type works.

**Comment by stevelizcano** [comment]
Hi! Here are some examples of how we do it:

```sql
-- name: CreateUser :one
INSERT INTO users (
    auth_id,
    email,
    name,
    team_id,
    subscription_active,
    photo_url,
    role
) VALUES (
    $1,
    $2,
    $3,
   typeid_parse(sqlc.arg(team_id)),
    $4,
    $5,
    $6
) RETURNING auth_id, typeid_print(id) as user_id, role, email, name;
```

and then in our `sqlc.yaml` we have:

```yaml
overrides:
  go:
    overrides:
      - db_type: "uuid"
        go_type: "github.com/google/uuid.UUID"
      - db_type: "typeid"
        go_type: "go.jetpack.io/typeid.TypeID"
      - db_type: "team_id"
        go_type: "github.com/staropshq/scribeiq/domains.PGTypeID"
      - db_type: "team_id"
        go_type: "github.com/staropshq/scribeiq/domains.PGTypeID"
        nullable: true
      - db_type: "user_id"
        go_type: "github.com/staropshq/scribeiq/domains.PGTypeID"
      - db_type: "user_id"
        go_type: "github.com/staropshq/scribeiq/domains.PGTypeID"
        nullable: true
```
